version: 2

models:
  - name: fct_user_engagement
    description: "用户在各课程中的整体学习参与情况，包括视频、阅读、题目、总互动数等"
    columns:
      - name: user_id
        description: "用户唯一标识"
        tests:
          - not_null
      - name: course_id
        description: "课程唯一标识"
        tests:
          - not_null
      - name: video_start_count
        description: "用户观看视频的次数"
      - name: video_complete_count
        description: "用户完整观看视频的次数"
      - name: total_video_duration
        description: "用户观看视频的总时长（秒）"
      - name: avg_read_percent
        description: "文章阅读平均百分比"
      - name: slide_view_count
        description: "幻灯片查看次数"
      - name: question_count
        description: "用户答题次数"
      - name: correct_count
        description: "答对题目数量"
      - name: correct_rate
        description: "答题正确率（百分比）"
      - name: total_events
        description: "该用户在课程中的所有事件总数"
      - name: last_event_time
        description: "最近一次事件的时间"

  - name: fct_content_engagement
    description: "每个课程内容项的总体参与情况，如视频观看、题目作答、阅读等"
    columns:
      - name: course_id
        description: "课程唯一标识"
        tests:
          - not_null
      - name: content_id
        description: "内容唯一标识"
        tests:
          - not_null
      - name: video_started_count
        description: "该内容作为视频被点击播放的次数"
      - name: video_completed_count
        description: "视频播放完成的次数"
      - name: total_video_duration
        description: "视频观看总时长"
      - name: avg_read_percent
        description: "内容作为文章时的平均阅读比例"
      - name: slide_viewed_count
        description: "内容作为幻灯片时的查看次数"
      - name: question_count
        description: "该内容包含的问题数量"
      - name: correct_count
        description: "被答对的题目数量"
      - name: correct_rate
        description: "题目正确率"
      - name: total_events
        description: "互动总数"
      - name: last_event_time
        description: "该内容最后一次被互动的时间"

  - name: fct_user_event_timeline
    description: "保留用户在每个课程内容上的完整行为轨迹，包含时间戳、事件类型及行为细节"
    columns:
      - name: user_id
        description: "用户唯一标识"
        tests:
          - not_null
      - name: course_id
        description: "课程唯一标识"
        tests:
          - not_null
      - name: lesson_id
        description: "所属课时"
      - name: content_id
        description: "互动的内容ID"
      - name: event_type
        description: "行为类型，如 video_started, question_submitted 等"
      - name: timestamp
        description: "事件发生时间"
      - name: video_duration
        description: "视频观看时长（秒）"
      - name: read_percent
        description: "阅读完成百分比"
      - name: slide_index
        description: "幻灯片索引"
      - name: question_id
        description: "题目ID"
      - name: answer_given
        description: "用户填写的答案"
      - name: is_correct
        description: "是否答对"
      - name: score
        description: "得分"
      - name: total_questions
        description: "总题数"
      - name: completion_ratio
        description: "完成度"

  - name: fct_user_content_summary
    description: "每个用户在各内容项上的完成情况，用于教学内容矩阵、行为覆盖率等分析"
    columns:
      - name: user_id
        description: "用户唯一标识"
        tests:
          - not_null
      - name: course_id
        description: "课程唯一标识"
        tests:
          - not_null
      - name: content_id
        description: "内容唯一标识"
        tests:
          - not_null
      - name: video_completed
        description: "是否完成视频观看（1=完成，0=未完成）"
      - name: article_read_completed
        description: "是否完成文章阅读（≥80%视为完成）"
      - name: slide_viewed
        description: "是否查看过幻灯片（1=有行为，0=无）"
      - name: question_answered
        description: "是否提交过题目答案"
      - name: is_content_completed
        description: "是否完成该内容（有任一行为即可视为完成）"
